//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COGERTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociacaoRecurso
    {
        public int Id { get; set; }
        public System.DateTime DataAssociacao { get; set; }
        public Nullable<System.DateTime> DataLiberacao { get; set; }
        public string MotivoLiberacao { get; set; }
        public string TermoResponsabilidade { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
