//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COGERTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra : Propriedade
    {
        public Nullable<System.DateTime> DataCompra { get; set; }
        public string PedidoSapNo { get; set; }
        public Nullable<System.DateTime> DataTerminoGarantia { get; set; }
    }
}
