//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COGERTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Equipamento : Recurso
    {
        public string SerialNo { get; set; }
        public Nullable<double> Patrimonio { get; set; }
        public Nullable<double> NotaFiscalNo { get; set; }
        public Nullable<System.DateTime> DataFabricacao { get; set; }
        public string StatusEquipamentoId { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
    
        public virtual StatusEquipamento StatusEquipamento { get; set; }
        public virtual Propriedade Propriedade { get; set; }
    }
}
