//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COGERTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinhaMovel : Recurso
    {
        public string LinhaNo { get; set; }
        public string ChipId { get; set; }
    
        public virtual CodigosDDD CodigosDDD { get; set; }
        public virtual TipoLinha TipoLinha { get; set; }
        public virtual TipoPlanoMovel TipoPlanoMovel { get; set; }
    }
}
