//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COGERTI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecursosDBContainer : DbContext
    {
        public RecursosDBContainer()
            : base("name=RecursosDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Funcionario> FuncionarioSet { get; set; }
        public virtual DbSet<CentroDeCusto> CentroDeCustoSet { get; set; }
        public virtual DbSet<Recurso> RecursoSet { get; set; }
        public virtual DbSet<LocalSite> LocalSiteSet { get; set; }
        public virtual DbSet<StatusFuncionario> StatusFuncionarioSet { get; set; }
        public virtual DbSet<AssociacaoRecurso> AssociacaoRecursoSet { get; set; }
        public virtual DbSet<StatusEquipamento> StatusEquipamentoSet { get; set; }
        public virtual DbSet<TipoComputador> TipoComputadorSet { get; set; }
        public virtual DbSet<Propriedade> PropriedadeSet { get; set; }
        public virtual DbSet<TipoAparelhoCelular> TipoAparelhoCelularSet { get; set; }
        public virtual DbSet<CodigosDDD> CodigosDDDSet { get; set; }
        public virtual DbSet<TipoLinha> TipoLinhaSet { get; set; }
        public virtual DbSet<TipoPlanoMovel> TipoPlanoMovelSet { get; set; }
    }
}
